# Generated by Django 3.1.2 on 2020-11-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appaccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
