# Generated by Django 3.1.2 on 2020-11-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appaccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.BooleanField(choices=[(1, 'MALE'), (0, 'FEMALE')], null=True),
        ),
    ]
