# Generated by Django 3.1.2 on 2020-11-29 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmarks', '0001_initial'),
        ('appaccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassesProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Lecture_Classes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('appmarks.classes',),
        ),
    ]
