# Generated by Django 3.1.2 on 2020-11-06 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appaccount', '0002_auto_20201104_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.BooleanField(blank=True, choices=[(1, 'MALE'), (0, 'FEMALE')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
