# Generated by Django 3.1.2 on 2020-11-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appaccount', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='images/avatar_default.png', upload_to='images/%Y/%m/%d/'),
        ),
    ]
