# Generated by Django 3.1.2 on 2020-11-11 15:07

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appaccount', '0003_auto_20201106_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUser',
            fields=[
            ],
            options={
                'verbose_name': 'Student',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('appaccount.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TeacherUser',
            fields=[
            ],
            options={
                'verbose_name': 'Teacher',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('appaccount.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.BooleanField(blank=True, choices=[(0, 'Nữ'), (1, 'Nam')], null=True),
        ),
    ]
