# Generated by Django 3.1.2 on 2020-11-03 12:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appaccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=10)),
                ('course_year', models.DateField(null=True)),
            ],
            options={
                'db_table': 'classes',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
                ('introduction', models.TextField(default='')),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appmarks.classes')),
            ],
            options={
                'db_table': 'lecture',
            },
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('from_year', models.DateField(null=True)),
                ('to_year', models.DateField(null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'schoolyear',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=50, null=True)),
                ('grades', models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(12)])),
                ('descriptions', models.TextField(default='', null=True)),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='appaccount.user')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teacher', to='appmarks.department')),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='appaccount.user')),
                ('is_crew', models.BooleanField(default=False)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appmarks.classes')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='MarksRegulary',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('semester', models.IntegerField(default=1, null=True)),
                ('test_date', models.DateTimeField()),
                ('times', models.IntegerField(default=1, null=True)),
                ('point', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('note', models.CharField(default='', max_length=200, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='marksregulary_lecture', to='appmarks.lecture')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='marksregulary_student', to='appmarks.student')),
            ],
            options={
                'db_table': 'marksregulary',
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('semester', models.IntegerField(default=1, null=True)),
                ('mid_semester_point', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('end_semester_point', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('gpa_semester_point', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('gpa_year_point', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('due_input', models.DateField()),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='marks_lecture', to='appmarks.lecture')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='marks_student', to='appmarks.student')),
            ],
            options={
                'db_table': 'marks',
            },
        ),
        migrations.AddField(
            model_name='lecture',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lecture', to='appmarks.schoolyear'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appmarks.subject'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appmarks.teacher'),
        ),
        migrations.CreateModel(
            name='ActivitiesClass',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appmarks.classes')),
                ('form_teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appmarks.teacher')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='activities_class', to='appmarks.schoolyear')),
            ],
            options={
                'db_table': 'activitiesclass',
            },
        ),
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gpa_first_semester', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('gpa_second_semester', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('gpa_year', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('conduct_stsemester', models.IntegerField(null=True)),
                ('conduct_ndsemester', models.IntegerField(null=True)),
                ('conduct_gpasemester', models.IntegerField(null=True)),
                ('rating', models.IntegerField(null=True)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='academic_record', to='appmarks.schoolyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appmarks.student')),
            ],
            options={
                'db_table': 'academicrecord',
            },
        ),
        migrations.AddConstraint(
            model_name='marks',
            constraint=models.UniqueConstraint(fields=('student', 'lecture', 'semester'), name='unique_student_lecture_semester'),
        ),
        migrations.AddConstraint(
            model_name='lecture',
            constraint=models.UniqueConstraint(fields=('teacher', 'subject', 'classes', 'school_year'), name='unique_lecture'),
        ),
        migrations.AddConstraint(
            model_name='academicrecord',
            constraint=models.UniqueConstraint(fields=('student', 'school_year'), name='unique_student_school_year'),
        ),
    ]
