# Generated by Django 3.1.2 on 2020-10-15 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appaccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'classes',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
                ('introduction', models.TextField(default='')),
            ],
            options={
                'db_table': 'deparment',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appmarks.classes')),
            ],
            options={
                'db_table': 'lecture',
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mid_first_semester', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('end_first_semester', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('gpa_first_semester', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('mid_second_semester', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('end_second_semester', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('gpa_second_semester', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('gpa_year', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('is_public', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appmarks.lecture')),
            ],
            options={
                'db_table': 'marks',
            },
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('from_year', models.DateField()),
                ('to_year', models.DateField()),
            ],
            options={
                'db_table': 'schoolyear',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='appaccount.user')),
                ('is_crew', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=50, null=True)),
                ('level', models.CharField(default='', max_length=10)),
                ('descriptions', models.TextField(default='', null=True)),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='appaccount.user')),
                ('deparment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appmarks.department')),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='MarksRegulary',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('test_date', models.DateTimeField()),
                ('point', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('note', models.CharField(default='', max_length=200, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('marks_ref', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appmarks.marks')),
            ],
            options={
                'db_table': 'marksregulary',
            },
        ),
        migrations.AddField(
            model_name='marks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appmarks.student'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appmarks.subject'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appmarks.teacher'),
        ),
        migrations.CreateModel(
            name='Conduct',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('conduct_stsemester', models.IntegerField()),
                ('conduct_ndsemester', models.IntegerField()),
                ('conduct_gpasemester', models.IntegerField()),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appmarks.classes')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appmarks.student')),
            ],
            options={
                'db_table': 'conduct',
            },
        ),
        migrations.AddField(
            model_name='classes',
            name='form_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appmarks.teacher'),
        ),
        migrations.AddField(
            model_name='classes',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appmarks.schoolyear'),
        ),
    ]
