# Generated by Django 3.1.2 on 2020-10-05 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appaccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('classes_name', models.CharField(max_length=10)),
                ('school_year', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
                ('introduction', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('semester', models.CharField(max_length=5)),
                ('school_year', models.CharField(max_length=10)),
                ('half_test', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('end_test', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('everage_test', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='appaccount.user')),
                ('deparment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appmarks.department')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=50, null=True)),
                ('descriptions', models.TextField(default='', null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appmarks.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='appaccount.user')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appmarks.classes')),
            ],
        ),
        migrations.CreateModel(
            name='MarksRegulary',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('test_date', models.DateTimeField()),
                ('marks', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('note', models.CharField(default='', max_length=200, null=True)),
                ('marks_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appmarks.marks')),
            ],
        ),
        migrations.AddField(
            model_name='marks',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appmarks.student'),
        ),
        migrations.AddField(
            model_name='marks',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appmarks.subject'),
        ),
        migrations.AddField(
            model_name='classes',
            name='form_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appmarks.teacher'),
        ),
    ]
