# Generated by Django 3.1.2 on 2020-10-16 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmarks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='deparment',
            new_name='department',
        ),
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
    ]
