# Generated by Django 3.1.2 on 2020-11-04 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmarks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='course_year',
            field=models.DateField(default=datetime.date(2020, 11, 4)),
        ),
        migrations.AlterField(
            model_name='marks',
            name='due_input',
            field=models.DateField(default=datetime.date(2020, 11, 4)),
        ),
        migrations.AlterField(
            model_name='marksregulary',
            name='test_date',
            field=models.DateTimeField(default=datetime.date(2020, 11, 4)),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='from_year',
            field=models.DateField(default=datetime.date(2020, 11, 4)),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='to_year',
            field=models.DateField(default=datetime.date(2020, 11, 4)),
        ),
    ]
