# Generated by Django 3.1.2 on 2020-11-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmarks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolyear',
            name='from_year',
            field=models.IntegerField(default=2020),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='to_year',
            field=models.IntegerField(default=2020),
        ),
    ]
