# Generated by Django 3.1.2 on 2020-11-13 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appmarks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marksregulary',
            name='lecture',
        ),
        migrations.AddField(
            model_name='marksregulary',
            name='marks_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='marksregulary', to='appmarks.marks'),
        ),
    ]
