# Generated by Django 3.1.2 on 2020-12-01 05:31

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appmarks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('post_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
