# Generated by Django 3.1.2 on 2020-11-04 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appmarks', '0002_auto_20201104_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksregulary',
            name='test_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
