# Generated by Django 3.1.2 on 2020-11-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmarks', '0002_auto_20201101_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksregulary',
            name='code_semester',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
