# Generated by Django 3.1.2 on 2020-12-01 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmarks', '0002_notice'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notice',
            table='notice',
        ),
    ]
