# Generated by Django 3.1.2 on 2020-11-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmarks', '0002_auto_20201120_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolyear',
            name='to_year',
            field=models.IntegerField(default=2021),
        ),
    ]
