# Generated by Django 3.1.2 on 2020-11-05 03:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmarks', '0003_auto_20201104_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='course_year',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='marks',
            name='due_input',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='from_year',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='to_year',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
