# Generated by Django 3.1.2 on 2020-11-08 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmarks', '0005_auto_20201106_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course_year',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_crew',
            field=models.BooleanField(choices=[(0, 'Chưa vào Đoàn'), (1, 'Đoàn viên')], default=False),
        ),
    ]
