# Generated by Django 3.1.2 on 2020-11-08 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appmarks', '0006_auto_20201108_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='course_year',
            field=models.IntegerField(default=2020),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
