# Generated by Django 3.1.2 on 2020-11-08 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmarks', '0007_auto_20201108_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='course_year',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='student',
            name='course_year',
            field=models.DateField(default=2020),
        ),
    ]
