# Generated by Django 3.1.2 on 2020-11-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmarks', '0008_auto_20201108_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_year',
            field=models.IntegerField(default=2020),
        ),
    ]
