# Generated by Django 3.1.2 on 2020-11-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmarks', '0009_auto_20201108_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='course_year',
            field=models.IntegerField(default=2020),
        ),
    ]
