# Generated by Django 3.1.2 on 2020-11-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmarks', '0010_auto_20201111_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='introduction',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddConstraint(
            model_name='classes',
            constraint=models.UniqueConstraint(fields=('class_name', 'course_year'), name='unique_classes'),
        ),
    ]
