# Generated by Django 3.1.2 on 2020-11-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmarks', '0011_auto_20201111_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_graduate',
            field=models.BooleanField(choices=[(0, 'Chưa tốt nghiệp'), (1, 'Đã tốt nghiệp')], default=False),
        ),
    ]
