# Generated by Django 3.1.2 on 2020-11-12 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appmarks', '0012_student_is_graduate'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicrecord',
            name='rating_ndsemester',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='academicrecord',
            name='rating_stsemester',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activitiesclass',
            name='classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='activities_class', to='appmarks.classes'),
        ),
        migrations.AlterField(
            model_name='activitiesclass',
            name='form_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='activities_class', to='appmarks.teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='classes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student', to='appmarks.classes'),
        ),
    ]
